### ISSUE TITLE
Support for encryption

### ISSUE THREAD

**Issue by ghost** [Milchdealer/sjcl-rust#1]

**Comment by Milchdealer** [comment]
I did not plan for it, as I am using it as a read-only library, but I believe it should be "fairly easy" doable with what's already there.

My main concern is that I am not a security researcher and I can't really make any guarantees about correctness..


Would you be willing to submit a PR, or a scaffold of how exactly such an interface would look like?

**Comment by SpheeresX** [comment]
Sorry for not responding, I was very busy this week. Unfortunately I can't submit a PR because I'm not good at Rust yet (I want to learn it by writing something that utilizes this library).

**Comment by Milchdealer** [comment]
No worries! Can you describe what you would expect as an interface.

For example what's the input, what's the output?

**Comment by SpheeresX** [comment]
I'd expect it should work closely to the existing decrypt function, i.e. `encrypt(data, password);`. Being able to change the PBKDF2 iteration count through a third argument would be nice.

**Comment by Milchdealer** [comment]
I‘ll see if I find time on the weekend to scrap something out :)

**Comment by Milchdealer** [comment]
Hey @SpheeresX,

I added encryption support in the branch `feature/1/encryption` and pushed it to github.

Check it out. I will probably push this soon, it will be a new major version (`1.0.0`) since I'm breaking some of the old functionality.
